version: '3.8'

services:
  # 后端服务
  backend:
    build: ./backend
    restart: always
    volumes:
      - ./backend:/app
      - ./backend/media:/app/media
      - ./backend/logs:/app/logs
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - app-network

  # 前端服务
  frontend:
    build: ./frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  # 数据库服务
  db:
    image: mysql:8.0
    restart: always
    env_file:
      - .env
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - app-network

  # Redis服务
  redis:
    image: redis:6.0
    restart: always
    volumes:
      - redis-data:/data
    ports:
      - "6380:6379"
    networks:
      - app-network

  # Celery Worker服务
  celery-worker:
    build: ./backend
    restart: always
    command: celery -A config worker -l info
    volumes:
      - ./backend:/app
      - ./backend/logs:/app/logs
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - backend
    networks:
      - app-network

  # Celery Beat服务
  celery-beat:
    build: ./backend
    restart: always
    command: celery -A config beat -l info
    volumes:
      - ./backend:/app
      - ./backend/logs:/app/logs
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
  redis-data: 