# Generated by Django 3.2 on 2025-03-08 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('testcases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='计划名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='计划描述')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('ready', '就绪'), ('in_progress', '进行中'), ('completed', '已完成'), ('archived', '已归档')], default='draft', max_length=20, verbose_name='状态')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_test_plans', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_plans', to='testcases.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '测试计划',
                'verbose_name_plural': '测试计划',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestPlanCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='执行顺序')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testcases.testcase', verbose_name='测试用例')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testplans.testplan', verbose_name='测试计划')),
            ],
            options={
                'verbose_name': '测试计划-用例关联',
                'verbose_name_plural': '测试计划-用例关联',
                'ordering': ['order'],
                'unique_together': {('plan', 'case')},
            },
        ),
        migrations.AddField(
            model_name='testplan',
            name='test_cases',
            field=models.ManyToManyField(related_name='test_plans', through='testplans.TestPlanCase', to='testcases.TestCase', verbose_name='测试用例'),
        ),
    ]
