# Generated by Django 4.2.16 on 2026-05-25 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testcases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('completed', '已完成'), ('failed', '执行失败'), ('canceled', '已取消')], default='pending', max_length=20, verbose_name='执行状态')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='实际开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='实际结束时间')),
                ('celery_task_id', models.CharField(blank=True, max_length=100, verbose_name='异步任务 ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('executor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_executions', to=settings.AUTH_USER_MODEL, verbose_name='执行人')),
            ],
            options={
                'verbose_name': '测试执行',
                'verbose_name_plural': '测试执行',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('passed', '通过'), ('failed', '失败'), ('blocked', '阻塞'), ('skipped', '跳过')], max_length=20, verbose_name='结果状态')),
                ('actual_result', models.TextField(blank=True, verbose_name='实际结果')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('attachments', models.JSONField(blank=True, default=list, verbose_name='附件信息')),
                ('executed_at', models.DateTimeField(blank=True, null=True, verbose_name='执行时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_results', to=settings.AUTH_USER_MODEL, verbose_name='执行人')),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='executions.testexecution', verbose_name='执行记录')),
                ('testcase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='testcases.testcase', verbose_name='测试用例')),
            ],
            options={
                'verbose_name': '测试结果',
                'verbose_name_plural': '测试结果',
                'ordering': ('testcase_id',),
            },
        ),
    ]
