# Generated by Django 3.2 on 2025-03-08 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('testcases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testplans', '0001_initial'),
        ('executions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('paused', '已暂停'), ('completed', '已完成'), ('aborted', '已中止')], default='pending', max_length=20, verbose_name='执行状态')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executed_tests', to=settings.AUTH_USER_MODEL, verbose_name='执行者')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='testplans.testplan', verbose_name='测试计划')),
            ],
            options={
                'verbose_name': '测试执行',
                'verbose_name_plural': '测试执行',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('passed', '通过'), ('failed', '失败'), ('blocked', '阻塞'), ('skipped', '跳过')], default='pending', max_length=20, verbose_name='结果状态')),
                ('actual_result', models.TextField(blank=True, null=True, verbose_name='实际结果')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('execution_time', models.DateTimeField(blank=True, null=True, verbose_name='执行时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='testcases.testcase', verbose_name='测试用例')),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='executions.testexecution', verbose_name='测试执行')),
                ('executor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to=settings.AUTH_USER_MODEL, verbose_name='执行者')),
            ],
            options={
                'verbose_name': '测试结果',
                'verbose_name_plural': '测试结果',
                'ordering': ['-updated_at'],
                'unique_together': {('execution', 'case')},
            },
        ),
    ]
