# Generated by Django 4.2.16 on 2026-05-25 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('testplans', '0001_initial'),
        ('executions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testexecution',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='testplans.testplan', verbose_name='测试计划'),
        ),
        migrations.AddConstraint(
            model_name='testresult',
            constraint=models.UniqueConstraint(fields=('execution', 'testcase'), name='unique_testcase_result_in_execution'),
        ),
    ]
