# Generated by Django 4.2.16 on 2026-05-28 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='用例名称')),
                ('description', models.TextField(blank=True, verbose_name='用例描述')),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE'), ('PATCH', 'PATCH')], default='GET', max_length=10, verbose_name='请求方法')),
                ('url', models.CharField(max_length=500, verbose_name='请求 URL')),
                ('headers', models.JSONField(blank=True, default=dict, verbose_name='请求头')),
                ('params', models.JSONField(blank=True, default=dict, verbose_name='URL 参数')),
                ('body_type', models.CharField(choices=[('none', '无'), ('json', 'JSON'), ('form-data', '表单数据'), ('x-www-form-urlencoded', 'URL编码表单'), ('raw', '原始文本')], default='none', max_length=30, verbose_name='请求体类型')),
                ('body', models.JSONField(blank=True, default=dict, verbose_name='请求体')),
                ('expected_status', models.IntegerField(default=200, verbose_name='期望状态码')),
                ('validation_rules', models.JSONField(blank=True, default=list, verbose_name='验证规则')),
                ('timeout', models.IntegerField(default=30, verbose_name='超时时间(秒)')),
                ('priority', models.CharField(choices=[('P0', 'P0'), ('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3')], default='P2', max_length=2, verbose_name='优先级')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '启用'), ('archived', '归档')], default='draft', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_api_testcases', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_testcases', to='projects.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '接口测试用例',
                'verbose_name_plural': '接口测试用例',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ApiTestExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='执行名称')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('completed', '已完成'), ('failed', '执行失败'), ('canceled', '已取消')], default='pending', max_length=20, verbose_name='执行状态')),
                ('total', models.IntegerField(default=0, verbose_name='总数')),
                ('passed', models.IntegerField(default=0, verbose_name='通过数')),
                ('failed', models.IntegerField(default=0, verbose_name='失败数')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('celery_task_id', models.CharField(blank=True, max_length=100, verbose_name='异步任务 ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('executor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_test_executions', to=settings.AUTH_USER_MODEL, verbose_name='执行人')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_executions', to='projects.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '接口测试执行',
                'verbose_name_plural': '接口测试执行',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ApiTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('passed', '通过'), ('failed', '失败'), ('error', '错误')], max_length=20, verbose_name='结果状态')),
                ('response_status', models.IntegerField(blank=True, null=True, verbose_name='响应状态码')),
                ('response_body', models.JSONField(blank=True, default=dict, verbose_name='响应体')),
                ('response_time', models.IntegerField(blank=True, null=True, verbose_name='响应时间(ms)')),
                ('validation_results', models.JSONField(blank=True, default=list, verbose_name='验证结果')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('executed_at', models.DateTimeField(blank=True, null=True, verbose_name='执行时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='apitests.apitestexecution', verbose_name='执行记录')),
                ('testcase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='apitests.apitestcase', verbose_name='测试用例')),
            ],
            options={
                'verbose_name': '接口测试结果',
                'verbose_name_plural': '接口测试结果',
                'ordering': ('testcase_id',),
            },
        ),
    ]
