# Generated by Django 4.2.16 on 2026-05-25 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('executions', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='报告名称')),
                ('summary', models.JSONField(blank=True, default=dict, verbose_name='报告摘要')),
                ('allure_report_path', models.CharField(blank=True, max_length=500, verbose_name='Allure 报告入口')),
                ('status', models.CharField(choices=[('pending', '待生成'), ('generated', '已生成'), ('failed', '生成失败')], default='pending', max_length=20, verbose_name='生成状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('execution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='executions.testexecution', verbose_name='执行记录')),
            ],
            options={
                'verbose_name': '测试报告',
                'verbose_name_plural': '测试报告',
                'ordering': ('-created_at',),
            },
        ),
    ]
