# Generated by Django 3.2 on 2025-03-10 05:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('executions', '0002_testexecution_testresult'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='报告名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='报告描述')),
                ('report_type', models.CharField(choices=[('allure', 'Allure报告'), ('html', 'HTML报告'), ('pdf', 'PDF报告')], default='allure', max_length=50, verbose_name='报告类型')),
                ('file_path', models.CharField(max_length=500, verbose_name='文件路径')),
                ('is_public', models.BooleanField(default=True, verbose_name='是否公开')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_reports', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='executions.testexecution', verbose_name='关联执行')),
            ],
            options={
                'verbose_name': '测试报告',
                'verbose_name_plural': '测试报告',
                'ordering': ['-created_at'],
            },
        ),
    ]
