# Generated by Django 4.2.16 on 2026-05-28 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UITestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='用例名称')),
                ('description', models.TextField(blank=True, verbose_name='用例描述')),
                ('browser', models.CharField(choices=[('chromium', 'Chromium'), ('firefox', 'Firefox'), ('webkit', 'WebKit')], default='chromium', max_length=20, verbose_name='浏览器')),
                ('headless', models.BooleanField(default=True, verbose_name='无头模式')),
                ('viewport_width', models.IntegerField(default=1280, verbose_name='视口宽度')),
                ('viewport_height', models.IntegerField(default=720, verbose_name='视口高度')),
                ('base_url', models.CharField(blank=True, max_length=500, verbose_name='基础URL')),
                ('steps', models.JSONField(blank=True, default=list, verbose_name='测试步骤')),
                ('timeout', models.IntegerField(default=30000, verbose_name='超时时间(毫秒)')),
                ('priority', models.CharField(choices=[('P0', 'P0'), ('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3')], default='P2', max_length=2, verbose_name='优先级')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '启用'), ('archived', '归档')], default='draft', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ui_testcases', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ui_testcases', to='projects.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': 'UI测试用例',
                'verbose_name_plural': 'UI测试用例',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='UITestExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='执行名称')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('completed', '已完成'), ('failed', '执行失败'), ('canceled', '已取消')], default='pending', max_length=20, verbose_name='执行状态')),
                ('total', models.IntegerField(default=0, verbose_name='总数')),
                ('passed', models.IntegerField(default=0, verbose_name='通过数')),
                ('failed', models.IntegerField(default=0, verbose_name='失败数')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('celery_task_id', models.CharField(blank=True, max_length=100, verbose_name='异步任务ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('executor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ui_test_executions', to=settings.AUTH_USER_MODEL, verbose_name='执行人')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ui_executions', to='projects.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': 'UI测试执行',
                'verbose_name_plural': 'UI测试执行',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='UITestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('passed', '通过'), ('failed', '失败'), ('error', '错误')], max_length=20, verbose_name='结果状态')),
                ('screenshot', models.TextField(blank=True, verbose_name='截图(BASE64)')),
                ('video_path', models.CharField(blank=True, max_length=500, verbose_name='视频路径')),
                ('logs', models.TextField(blank=True, verbose_name='执行日志')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='执行时长(毫秒)')),
                ('executed_at', models.DateTimeField(blank=True, null=True, verbose_name='执行时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='uitests.uitestexecution', verbose_name='执行记录')),
                ('testcase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='uitests.uitestcase', verbose_name='测试用例')),
            ],
            options={
                'verbose_name': 'UI测试结果',
                'verbose_name_plural': 'UI测试结果',
                'ordering': ('testcase_id',),
            },
        ),
    ]
